# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"win": "game.ipynb",
         "lose": "game.ipynb",
         "KingAlbert": "game.ipynb"}

modules = ["game.py"]

doc_url = "https://thecharlieblake.github.io/solitairenet/"

git_url = "https://github.com/thecharlieblake/solitairenet/tree/master/"

def custom_doc_links(name): return None
