# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://thecharlieblake.github.io/solitairenet/"

git_url = "https://github.com/thecharlieblake/solitairenet/tree/master/"

def custom_doc_links(name): return None
