# AUTOGENERATED! DO NOT EDIT! File to edit: game.ipynb (unless otherwise specified).

__all__ = ['win', 'lose', 'KingAlbert']

# Cell
print("test")
import numpy as           np

# Cell
def win(player):
    "Print win message"
    return f'{player} has won!'

def lose(player):
    "Print loss message"
    return f'{player} has lost!'

# Cell
class KingAlbert:
    "A game of King Albert for player `player`, using `win` and `lose`"
    def __init__(self, player, status=(np.random.rand() > .5)):
        self.player = player
        self.status = status

    def final_msg(self):
        "Find out if you've won or lost"
        return (win if self.status else lose)(self.player)