# AUTOGENERATED! DO NOT EDIT! File to edit: game.ipynb (unless otherwise specified).

__all__ = ['win', 'lose']

# Cell
import numpy as np

# Cell
def win(player):
    "Print win message"
    return f'{player} has won!'

def lose(player):
    "Print loss message"
    return f'{player} has lost!'